### ISSUE TITLE
Can we add a functionality which can help read existing CoreData, both encrypted and normal one?

### ISSUE THREAD

**Issue by paragdulam** [radianttap/RTSwiftCoreDataStack#3] opened 2019-03-04 08:42 UTC

**Comment by radianttap** [comment] 2019-03-04 18:43
Is this the same thing as #2 ?

**Comment by paragdulam** [comment] 2019-03-04 19:23
Yes kind of. Only difference is whether this library is able to read existing encrypted sqlite file managed by core data. So the developer can change one line in Podfile and a few in code to make it work?

**Comment by radianttap** [comment] 2019-03-04 21:07
duplicate of #2

**Closed as completed by radianttap** 2019-03-04 21:07 UTC
Labels: duplicate
